name: messy_client
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #state managment
  flutter_bloc: ^8.1.6

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  #data manipulating
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  #REST
  dio: ^5.7.0

  #websockets
  socket_io_client: ^3.0.0
  web_socket_channel: ^3.0.1

  #UI
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  sms_autofill: ^2.4.0
  skeletonizer: ^1.4.2
  rive: ^0.13.13
  country_flags: ^3.0.0
  
  #router
  go_router: ^14.2.7

  #DI
  get_it: ^7.7.0
  
  #geolocation
  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
      - assets/rives/
  
